// AUTO-GENERATED. Do not edit manually.
// Generated at: 2026-01-14T18:12:51.343Z

export const INDEX = {
  "01": require("../../assets/locations/districts/01.json"),
  "02": require("../../assets/locations/districts/02.json"),
  "04": require("../../assets/locations/districts/04.json"),
  "06": require("../../assets/locations/districts/06.json"),
  "08": require("../../assets/locations/districts/08.json"),
  "10": require("../../assets/locations/districts/10.json"),
  "11": require("../../assets/locations/districts/11.json"),
  "12": require("../../assets/locations/districts/12.json"),
  "14": require("../../assets/locations/districts/14.json"),
  "15": require("../../assets/locations/districts/15.json"),
  "17": require("../../assets/locations/districts/17.json"),
  "19": require("../../assets/locations/districts/19.json"),
  "20": require("../../assets/locations/districts/20.json"),
  "22": require("../../assets/locations/districts/22.json"),
  "24": require("../../assets/locations/districts/24.json"),
  "25": require("../../assets/locations/districts/25.json"),
  "26": require("../../assets/locations/districts/26.json"),
  "27": require("../../assets/locations/districts/27.json"),
  "30": require("../../assets/locations/districts/30.json"),
  "31": require("../../assets/locations/districts/31.json"),
  "33": require("../../assets/locations/districts/33.json"),
  "34": require("../../assets/locations/districts/34.json"),
  "35": require("../../assets/locations/districts/35.json"),
  "36": require("../../assets/locations/districts/36.json"),
  "37": require("../../assets/locations/districts/37.json"),
  "38": require("../../assets/locations/districts/38.json"),
  "40": require("../../assets/locations/districts/40.json"),
  "42": require("../../assets/locations/districts/42.json"),
  "44": require("../../assets/locations/districts/44.json"),
  "45": require("../../assets/locations/districts/45.json"),
  "46": require("../../assets/locations/districts/46.json"),
  "48": require("../../assets/locations/districts/48.json"),
  "49": require("../../assets/locations/districts/49.json"),
  "51": require("../../assets/locations/districts/51.json"),
  "52": require("../../assets/locations/districts/52.json"),
  "54": require("../../assets/locations/districts/54.json"),
  "56": require("../../assets/locations/districts/56.json"),
  "58": require("../../assets/locations/districts/58.json"),
  "60": require("../../assets/locations/districts/60.json"),
  "62": require("../../assets/locations/districts/62.json"),
  "64": require("../../assets/locations/districts/64.json"),
  "66": require("../../assets/locations/districts/66.json"),
  "67": require("../../assets/locations/districts/67.json"),
  "68": require("../../assets/locations/districts/68.json"),
  "70": require("../../assets/locations/districts/70.json"),
  "72": require("../../assets/locations/districts/72.json"),
  "74": require("../../assets/locations/districts/74.json"),
  "75": require("../../assets/locations/districts/75.json"),
  "77": require("../../assets/locations/districts/77.json"),
  "79": require("../../assets/locations/districts/79.json"),
  "80": require("../../assets/locations/districts/80.json"),
  "82": require("../../assets/locations/districts/82.json"),
  "83": require("../../assets/locations/districts/83.json"),
  "84": require("../../assets/locations/districts/84.json"),
  "86": require("../../assets/locations/districts/86.json"),
  "87": require("../../assets/locations/districts/87.json"),
  "89": require("../../assets/locations/districts/89.json"),
  "91": require("../../assets/locations/districts/91.json"),
  "92": require("../../assets/locations/districts/92.json"),
  "93": require("../../assets/locations/districts/93.json"),
  "94": require("../../assets/locations/districts/94.json"),
  "95": require("../../assets/locations/districts/95.json"),
  "96": require("../../assets/locations/districts/96.json"),
};

export default INDEX;
